# -------------------------------------------------------------------------
# Reset generated project outputs:
# -------------------------------------------------------------------------
#
# This script removes generated data, models, reports and plots
# while keeping the original raw input images.
#
# It is used before rerunning the full project pipeline from scratch.
#
# The CNN and Random Forest architecture visualizations are not removed,
# because they are stored separately in:
#
# results/visualizations/
# -------------------------------------------------------------------------


import os
import shutil


# folders that are generated by the data and training pipeline
PATHS_TO_REMOVE = [
    "data/augmented",
    "data/model_dataset",
    "data/streamlit_demo",
    "models",
    "results/reports",
    "results/plots",
]

# generated files outside the report/plot folders
FILES_TO_REMOVE = [
    "results/augmentation_metadata.csv",
]


# ------------------------------------------------------------
# Remove generated folders
# ------------------------------------------------------------

for path in PATHS_TO_REMOVE:

    if os.path.exists(path):
        shutil.rmtree(path)
        print(f"Removed folder: {path}")


# ------------------------------------------------------------
# Remove generated files
# ------------------------------------------------------------

for file_path in FILES_TO_REMOVE:

    if os.path.exists(file_path):
        os.remove(file_path)
        print(f"Removed file: {file_path}")


print("Generated outputs reset complete.")